elementsofhealing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('contact/', include('contact.urls')),
    path('appointments/', include('appointments.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from pages import views


urlpatterns = [
    path('', views.home, name='home'),
    path('homeopathy/', views.homeopathy, name='homeopathy'),
    path('consultation/', views.consultation, name='consultation'),
    path('about/', views.about, name='about'),
]

products/urls.py
from django.urls import path
from products import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('update/<int:product_id>/', views.update_product, name='update_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

checkout/models.py
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    potency = models.CharField(max_length=4, null=True, blank=True) # 6c, 30c, 200c 1M, 10M
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_potency = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-style-input'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower
from django.contrib.auth.decorators import login_required
from .models import Product, Category
from .forms import ProductForm


def all_products(request):
    """ A view to show all remedies and remedy kits, including sorting and search queries """
    if not request.user.is_authenticated:
        messages.error(request, 'Sorry, only registered users can purchase products on this site.')
        return redirect(reverse('home'))

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual remedies and remedy kits """
    if not request.user.is_authenticated:
        messages.error(request, 'Sorry, only registered users can purchase products on this site.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def update_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/update_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock extra_css %}

{% block content %}
<section class="container dark-bg">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-11 col-md-10 col-lg-9 form box">
            <h2>Product Management</h2>
            <h3>Add a Product</h3>
            <form method="POST" action="{% url 'add_product' %}" enctype="multipart/form-data">
                <div class="inner-box--grey">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                </div>
                <button class="btn form-btn" type="submit">Add Product</button>
                <a class="btn form-btn" href="{% url 'products' %}">Cancel</a>
            </form>
        </div>
    </div>
</section>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock extra_css %}

{% block content %}
<section class="container dark-bg">
    <div class="row justify-content-center">
        <div class="col-11 col-sm-9 col-md-8 col-lg-6">
            <div class="card product-item inner-box--black">
                <h2>{{product.name}}</h2>
                {% if product.image %}
                <a class="product-img-link" href="{{ product.image.url }}">
                    <img class="card-img" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a class="product-img-link" href="">
                    <img class="card-img" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
                <div class="card-body">
                    <p>{{ product.name }} - {{ product.description }}</p>
                    <p><span>£{{ product.price }}</span></p>
                    {% if product.rating %}
                        <p><span><i class="fas fa-star"></i>{{ product.rating }} / 5</span></p>
                    {% else %}
                        <p><span>No Rating</span></p>
                    {% endif %}
                    {% if product.category %}
                    <p>
                        <a href="{% url 'products' %}?category={{ product.category.name }}">
                            <i class="fas fa-tag"></i>{{ product.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}
                    {% if request.user.is_superuser %}
                    <p>
                        <a class="text-info" href="{% url 'update_product' product.id %}"><i class="fas fa-edit"></i>Update</a>
                    </p>
                    <p>
                        <a class="text-danger" href="{% url 'delete_product' product.id %}"><i class="fas fa-trash-alt"></i>Delete</a>
                    </p>
                    {% endif %}
                </div>
                <div class="card-footer">
                    <form class="form product-info" action="{% url 'add_to_basket' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            {% with product.has_potency as p %}
                            {% if p %}
                            <div class="form-group col-12">
                                <label>Potency:</label>
                                <select class="form-control" name="potency" id="id_potency">
                                    <option value="6c">6c</option>
                                    <option value="30c" selected>30c</option>
                                    <option value="200c">200c</option>
                                    <option value="1M">1M</option>
                                    <option value="10M">10M</option>
                                </select>
                            </div>
                            {% endif %}
                            {% endwith %}
                            <div class="form-group col-12">
                                <label>Quantity:</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button id="decrement-qty_{{ product.id }}" class="decrement-qty btn custom-btn" data-item_id="{{ product.id }}">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                    </div>
                                    <input id="id_qty_{{ product.id }}" class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}">
                                    <div class="input-group-append">
                                        <button id="increment-qty_{{ product.id }}" class="increment-qty btn custom-btn" data-item_id="{{ product.id }}">
                                            <i class="fas fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-12">
                                <a href="{% url 'products' %}" class="btn shopping-btn">
                                    <span ><i class="fas fa-chevron-left"></i></span>
                                    <span class="">Keep Shopping</span>
                                </a>
                                <input type="submit" class="btn shopping-btn" value="Add to Basket">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock extra_css %}

{% block page_navbar %}
<nav class="navbar navbar-expand-sm navbar-dark container d-none d-sm-block">
    <ul class="navbar-nav justify-content-center">
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">All Products</a>
            <div class="dropdown-menu">
                <a class="nav-link dropdown-item" href="{% url 'products' %}?sort=price&direction=asc">By Price</a>
                <a class="nav-link dropdown-item" href="{% url 'products' %}?sort=rating&direction=desc">By Rating</a>
                <a class="nav-link dropdown-item" href="{% url 'products' %}?sort=category&direction=asc">By Category</a>
                <a class="nav-link dropdown-item" href="{% url 'products' %}">All Products</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'products' %}?category=appointments">Appointments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'products' %}?category=remedy_kits">Kits</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'products' %}?category=individual_remedies">Remedies</a>
        </li>
    </ul>
</nav>
{% endblock page_navbar %}

{% block content %}
<section class="container dark-bg">
    <div class="row justify-content-center">
        <div class="col-12">
            {% if current_categories == None %}
            <h1>Homeopathic Services & Products</h1>
            {% else %}
                {% for c in current_categories %}
                <h1>Homeopathic {{ c.friendly_name }}</h1>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center no-gutters">
        <div class="col-12 col-md-6 sort-select-summary">
            <p>
            {% if search_term or current_categories or current_sorting != 'None_None' %}
                <a href="{% url 'products' %}">Products Home</a><span>|</span>
            {% endif %}
                <span>{{ products|length }} Products{% if search_term %} found for"{{ search_term }}"{% endif %}</span>
            </p>
        </div>
        <div class="col-6 col-md-4 col-lg-3">
            <div class="sort-select-wrapper">
                <select id="sortSelector" class="custom-select custom-select-sm border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                    <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                    <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)</option>
                    <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)</option>
                    <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating (low to high)</option>
                    <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to low)</option>
                    <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                    <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                    <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category (A-Z)</option>
                    <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category (Z-A)</option>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-8 offset-2 col-sm-10 offset-sm-1 col-lg-12 offset-lg-0">
            <div class="row">
                {% for product in products %}
                <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                    <div class="card product-item inner-box--black">
                        {% if product.category.friendly_name == "Appointments" %}
                        <a href="{% url 'appointments' product.id %}">
                        {% else %}
                        <a href="{% url 'product_detail' product.id %}">
                        {% endif %}
                            <div class="overlay-container">
                                {% if product.image %}
                                <img class="card-img" src="{{ product.image.url }}" alt="{{ product.name }}">
                                {% else %}
                                <img class="card-img" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                                {% endif %}
                                <div class="overlay">
                                    <div class="overlay-text">
                                    {% if product.category.friendly_name == "Appointments" %}Book Appointment{% else %}Purchase {{ product.name }}{% endif %}</div>
                                </div>
                            </div>
                        </a>
                        <div class="card-body">
                            <p>{{ product.name }}</p>
                            <p><span>£{{ product.price }}</span></p>
                            {% if product.rating %}
                                <p><span><i class="fas fa-star"></i>{{ product.rating }} / 5</span></p>
                            {% else %}
                                <p><span>No Rating</span></p>
                            {% endif %}
                            {% if product.category %}
                            <p>
                                <a href="{% url 'products' %}?category={{ product.category.name }}">
                                    <span><i class="fas fa-tag"></i>{{ product.category.friendly_name }}</span>
                                </a>
                            </p>
                            {% endif %}
                            {% if request.user.is_superuser %}
                            <p>
                                <a class="text-info" href="{% url 'update_product' product.id %}"><i class="fas fa-edit"></i>Update</a>
                            </p>
                            <p>
                                <a class="text-danger" href="{% url 'delete_product' product.id %}"><i class="fas fa-trash-alt"></i>Delete</a>
                            </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block postloadjs %}
{{ block.super }}

<script>

let sortSelector = document.getElementById("sortSelector");

sortSelector.addEventListener("change", function(e){
    let url = new URL(window.location);
    let selectVal = e.target.value;
    if(selectVal != "reset") {
        let sort = selectVal.split("_")[0];
        let direction = selectVal.split("_")[1];
        url.searchParams.set("sort", sort);
        url.searchParams.set("direction", direction);
        window.location.replace(url);
    } else {
        url.searchParams.delete("sort");
        url.searchParams.delete("direction");
        window.location.replace(url);
    }
}, false);

</script>

{% endblock postloadjs %}

products/templates/products/update_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock extra_css %}

{% block content %}
<section class="container dark-bg">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-11 col-md-10 col-lg-9 form box">
            <h2>Product Management</h2>
            <h3>Update a Product</h3>
            <form method="POST" action="{% url 'update_product' product.id %}" enctype="multipart/form-data">
                <div class="inner-box--grey">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                </div>
                <button class="btn form-btn" type="submit">Update Product</button>
                <a class="btn form-btn" href="{% url 'products' %}">Cancel</a>
            </form>
        </div>
    </div>
</section>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}